//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OCR.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("train-images.idx3-ubyte")]
        public string ImageApprentissage {
            get {
                return ((string)(this["ImageApprentissage"]));
            }
            set {
                this["ImageApprentissage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("train-labels.idx1-ubyte")]
        public string LabelApprentissage {
            get {
                return ((string)(this["LabelApprentissage"]));
            }
            set {
                this["LabelApprentissage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("t10k-images.idx3-ubyte")]
        public string ImageTest {
            get {
                return ((string)(this["ImageTest"]));
            }
            set {
                this["ImageTest"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("t10k-labels.idx1-ubyte")]
        public string LabelTest {
            get {
                return ((string)(this["LabelTest"]));
            }
            set {
                this["LabelTest"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("120000")]
        public string NbPalierBackpropagation {
            get {
                return ((string)(this["NbPalierBackpropagation"]));
            }
            set {
                this["NbPalierBackpropagation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0,794183335")]
        public string Eta {
            get {
                return ((string)(this["Eta"]));
            }
            set {
                this["Eta"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0,00005")]
        public string MinimumEta {
            get {
                return ((string)(this["MinimumEta"]));
            }
            set {
                this["MinimumEta"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0,001")]
        public string EtaInitial {
            get {
                return ((string)(this["EtaInitial"]));
            }
            set {
                this["EtaInitial"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string Chiffres_P {
            get {
                return ((string)(this["Chiffres_P"]));
            }
            set {
                this["Chiffres_P"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public string Minuscules_P {
            get {
                return ((string)(this["Minuscules_P"]));
            }
            set {
                this["Minuscules_P"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public string Majuscules_P {
            get {
                return ((string)(this["Majuscules_P"]));
            }
            set {
                this["Majuscules_P"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public string Chiffres_M {
            get {
                return ((string)(this["Chiffres_M"]));
            }
            set {
                this["Chiffres_M"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public string Majuscules_M {
            get {
                return ((string)(this["Majuscules_M"]));
            }
            set {
                this["Majuscules_M"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public string Minuscules_M {
            get {
                return ((string)(this["Minuscules_M"]));
            }
            set {
                this["Minuscules_M"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("transco.txt")]
        public string Transco {
            get {
                return ((string)(this["Transco"]));
            }
            set {
                this["Transco"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Chiffres_Printed.txt")]
        public string Chiffres_Printed {
            get {
                return ((string)(this["Chiffres_Printed"]));
            }
            set {
                this["Chiffres_Printed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Majuscules_Printed.txt")]
        public string Majuscules_Printed {
            get {
                return ((string)(this["Majuscules_Printed"]));
            }
            set {
                this["Majuscules_Printed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Minuscules_Printed.txt")]
        public string Minuscules_Printed {
            get {
                return ((string)(this["Minuscules_Printed"]));
            }
            set {
                this["Minuscules_Printed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\BaseData")]
        public string PathMnist {
            get {
                return ((string)(this["PathMnist"]));
            }
            set {
                this["PathMnist"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double EstimatedCurrentMSE {
            get {
                return ((double)(this["EstimatedCurrentMSE"]));
            }
            set {
                this["EstimatedCurrentMSE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\BaseData\\Fnt")]
        public string PathPolicesMajuscules {
            get {
                return ((string)(this["PathPolicesMajuscules"]));
            }
            set {
                this["PathPolicesMajuscules"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Traitement\\parametrage")]
        public string Parametrage {
            get {
                return ((string)(this["Parametrage"]));
            }
            set {
                this["Parametrage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\BaseData\\Fnt")]
        public string PathPolicesMinuscules {
            get {
                return ((string)(this["PathPolicesMinuscules"]));
            }
            set {
                this["PathPolicesMinuscules"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\BaseData\\Fnt")]
        public string PathPolicesChiffres {
            get {
                return ((string)(this["PathPolicesChiffres"]));
            }
            set {
                this["PathPolicesChiffres"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\BaseData\\Police\\Autres")]
        public string PathPolicesAutres {
            get {
                return ((string)(this["PathPolicesAutres"]));
            }
            set {
                this["PathPolicesAutres"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Majuscules_Printed.txt")]
        public string ImagesTestCaracteresImrpimes {
            get {
                return ((string)(this["ImagesTestCaracteresImrpimes"]));
            }
            set {
                this["ImagesTestCaracteresImrpimes"] = value;
            }
        }
    }
}
